disabled_rules: # Rule identifiers to exclude from running
  - colon # Exaclty one space after the : >>> let abc: Void\n
  - control_statement # No rounded brackets around conditions. we would need this the other way around
  - todo # TODO can be written in the code but should be linked to a ticket on JIRA.
  - nesting # Func nesting max 1 level
  - cyclomatic_complexity # Limit the number of entries inside an enum or struct.
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - closure_parameter_position
  - redundant_string_enum_value
  - vertical_parameter_alignment
  - trailing_whitespace

excluded: # paths to ignore during linting. overridden by `included`.
  - Pods

# rule parameters
file_length:
  - 600 #warning
  - 800 #error

function_body_length:
  - 40 #warning
  - 80 #error

line_length:
  - 300 #warning
  - 350 #error

type_body_length:
  - 400 #warning
  - 500 #error

large_tuple:
  - 4 #warning
  - 6 #error

allow_private_set:
 - allow_private_set: true

